<a href="https://colab.research.google.com/github/aryann402/data-science/blob/main/Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
import pandas as pd
pd.read_csv("/content/drive/MyDrive/World Cup 2018 Dataset.csv")

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN
5,Spain,B,14.0,1.0,1.0,2.0,6.0,Portugal,3.0,12.0,31.0,Iran,20.0,NaN,NaN,Morocco,36.0,5.0,7.0,NaN
6,Morocco,B,4.0,0.0,0.0,0.0,40.0,Iran,4.0,-2.0,-2.0,Portugal,19.0,1.0,2.0,Spain,36.0,-5.0,-7.0,NaN
7,IRAN,B,4.0,0.0,0.0,0.0,32.0,Morocco,4.0,2.0,2.0,Spain,20.0,NaN,NaN,Portugal,35.0,-2.0,-5.0,NaN
8,France,C,14.0,1.0,2.0,5.0,9.0,Australia,5.0,1.0,6.0,Peru,21.0,-1.0,-1.0,Denmark,37.0,4.0,9.0,NaN
9,Australia,C,4.0,0.0,0.0,0.0,39.0,France,5.0,-1.0,-6.0,Denmark,22.0,-1.0,-3.0,Peru,38.0,NaN,NaN,NaN
10,Peru,C,4.0,0.0,0.0,0.0,11.0,Denmark,6.0,NaN,NaN,France,21.0,1.0,1.0,Australia,38.0,NaN,NaN,NaN
11,Denmark,C,4.0,0.0,0.0,0.0,12.0,Peru,6.0,NaN,NaN,Australia,22.0,1.0,3.0,France,37.0,-4.0,-9.0,NaN
12,Argentina,D,16.0,2.0,5.0,5.0,4.0,Iceland,7.0,NaN,NaN,Croatia,23.0,1.0,0.0,Nigeria,39.0,3.0,1.0,NaN
13,Iceland,D,0.0,0.0,0.0,0.0,22.0,Argentina,7.0,NaN,NaN,Nigeria,24.0,1.0,3.0,Croatia,40.0,-3.0,-9.0,NaN
14,Croatia,D,4.0,0.0,0.0,1.0,17.0,Nigeria,8.0,NaN,NaN,Argentina,23.0,-1.0,0.0,Iceland,40.0,3.0,9.0,NaN
15,Nigeria,D,5.0,0.0,0.0,0.0,50.0,Croatia,8.0,NaN,NaN,Iceland,24.0,-1.0,-3.0,Argentina,39.0,-3.0,-1.0,NaN
16,Brazil,E,20.0,5.0,7.0,11.0,2.0,Switzerland,9.0,1.0,2.0,Costarica,25.0,8.0,19.0,Serbia,41.0,1.0,1.0,NaN
17,Switzerland,E,10.0,0.0,0.0,0.0,8.0,Brazil,9.0,-1.0,-2.0,Serbia,26.0,NaN,NaN,Costarica,42.0,0.0,1.0,NaN
18,Costarica,E,4.0,0.0,0.0,0.0,26.0,Serbia,10.0,NaN,NaN,Brazil,25.0,-8.0,-19.0,Switzerland,42.0,0.0,-1.0,NaN
19,Serbia,E,11.0,0.0,0.0,2.0,37.0,Costarica,10.0,NaN,NaN,Switzerland,26.0,NaN,NaN,Brazil,41.0,-1.0,-1.0,NaN
20,Germany,F,18.0,4.0,8.0,13.0,1.0,Mexico,11.0,4.0,13.0,Sweden,27.0,2.0,10.0,Korea,43.0,1.0,0.0,NaN
21,Mexico,F,15.0,0.0,0.0,0.0,16.0,Germany,11.0,-4.0,-13.0,Korea,28.0,1.0,12.0,Sweden,44.0,-2.0,-3.0,NaN
22,Sweden,F,11.0,0.0,1.0,4.0,18.0,Korea,12.0,1.0,2.0,Germany,27.0,-2.0,-10.0,Mexico,44.0,2.0,3.0,NaN
23,Korea,F,9.0,0.0,0.0,1.0,59.0,Sweden,12.0,-1.0,-2.0,Mexico,28.0,-1.0,-10.0,Germany,43.0,-1.0,0.0,NaN
24,Belgium,G,12.0,0.0,0.0,1.0,5.0,Panama,13.0,NaN,NaN,Tunisia,29.0,0.0,0.0,England,45.0,-17.0,-70.0,NaN
25,Panama,G,0.0,0.0,0.0,0.0,56.0,Belgium,13.0,NaN,NaN,England,30.0,NaN,NaN,Tunisia,46.0,NaN,NaN,NaN
26,Tunisia,G,4.0,0.0,0.0,0.0,27.0,England,14.0,-1.0,-2.0,Belgium,29.0,0.0,0.0,Panama,46.0,NaN,NaN,NaN
27,England,G,14.0,1.0,1.0,2.0,15.0,Tunisia,14.0,1.0,2.0,Panama,30.0,NaN,NaN,Belgium,45.0,17.0,70.0,NaN
28,Poland,H,7.0,0.0,0.0,2.0,7.0,Senegal,15.0,NaN,NaN,Columbia,31.0,NaN,NaN,Japan,47.0,2.0,3.0,NaN
29,Senegal,H,1.0,0.0,0.0,0.0,23.0,Poland,15.0,NaN,NaN,Japan,32.0,2.0,3.0,Columbia,48.0,0.0,0.0,NaN
30,Columbia,H,5.0,0.0,0.0,0.0,13.0,Japan,16.0,2.0,2.0,Poland,31.0,NaN,NaN,Senegal,48.0,0.0,0.0,NaN
31,Japan,H,5.0,0.0,0.0,0.0,55.0,Columbia,16.0,-2.0,-2.0,Senegal,32.0,-2.0,-3.0,Poland,47.0,-2.0,-3.0,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
import pandas as pd
dataframe = pd.read_csv("/content/drive/MyDrive/World Cup 2018 Dataset.csv")
dataframe

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN
5,Spain,B,14.0,1.0,1.0,2.0,6.0,Portugal,3.0,12.0,31.0,Iran,20.0,NaN,NaN,Morocco,36.0,5.0,7.0,NaN
6,Morocco,B,4.0,0.0,0.0,0.0,40.0,Iran,4.0,-2.0,-2.0,Portugal,19.0,1.0,2.0,Spain,36.0,-5.0,-7.0,NaN
7,IRAN,B,4.0,0.0,0.0,0.0,32.0,Morocco,4.0,2.0,2.0,Spain,20.0,NaN,NaN,Portugal,35.0,-2.0,-5.0,NaN
8,France,C,14.0,1.0,2.0,5.0,9.0,Australia,5.0,1.0,6.0,Peru,21.0,-1.0,-1.0,Denmark,37.0,4.0,9.0,NaN
9,Australia,C,4.0,0.0,0.0,0.0,39.0,France,5.0,-1.0,-6.0,Denmark,22.0,-1.0,-3.0,Peru,38.0,NaN,NaN,NaN
10,Peru,C,4.0,0.0,0.0,0.0,11.0,Denmark,6.0,NaN,NaN,France,21.0,1.0,1.0,Australia,38.0,NaN,NaN,NaN
11,Denmark,C,4.0,0.0,0.0,0.0,12.0,Peru,6.0,NaN,NaN,Australia,22.0,1.0,3.0,France,37.0,-4.0,-9.0,NaN
12,Argentina,D,16.0,2.0,5.0,5.0,4.0,Iceland,7.0,NaN,NaN,Croatia,23.0,1.0,0.0,Nigeria,39.0,3.0,1.0,NaN
13,Iceland,D,0.0,0.0,0.0,0.0,22.0,Argentina,7.0,NaN,NaN,Nigeria,24.0,1.0,3.0,Croatia,40.0,-3.0,-9.0,NaN
14,Croatia,D,4.0,0.0,0.0,1.0,17.0,Nigeria,8.0,NaN,NaN,Argentina,23.0,-1.0,0.0,Iceland,40.0,3.0,9.0,NaN
15,Nigeria,D,5.0,0.0,0.0,0.0,50.0,Croatia,8.0,NaN,NaN,Iceland,24.0,-1.0,-3.0,Argentina,39.0,-3.0,-1.0,NaN
16,Brazil,E,20.0,5.0,7.0,11.0,2.0,Switzerland,9.0,1.0,2.0,Costarica,25.0,8.0,19.0,Serbia,41.0,1.0,1.0,NaN
17,Switzerland,E,10.0,0.0,0.0,0.0,8.0,Brazil,9.0,-1.0,-2.0,Serbia,26.0,NaN,NaN,Costarica,42.0,0.0,1.0,NaN
18,Costarica,E,4.0,0.0,0.0,0.0,26.0,Serbia,10.0,NaN,NaN,Brazil,25.0,-8.0,-19.0,Switzerland,42.0,0.0,-1.0,NaN
19,Serbia,E,11.0,0.0,0.0,2.0,37.0,Costarica,10.0,NaN,NaN,Switzerland,26.0,NaN,NaN,Brazil,41.0,-1.0,-1.0,NaN
20,Germany,F,18.0,4.0,8.0,13.0,1.0,Mexico,11.0,4.0,13.0,Sweden,27.0,2.0,10.0,Korea,43.0,1.0,0.0,NaN
21,Mexico,F,15.0,0.0,0.0,0.0,16.0,Germany,11.0,-4.0,-13.0,Korea,28.0,1.0,12.0,Sweden,44.0,-2.0,-3.0,NaN
22,Sweden,F,11.0,0.0,1.0,4.0,18.0,Korea,12.0,1.0,2.0,Germany,27.0,-2.0,-10.0,Mexico,44.0,2.0,3.0,NaN
23,Korea,F,9.0,0.0,0.0,1.0,59.0,Sweden,12.0,-1.0,-2.0,Mexico,28.0,-1.0,-10.0,Germany,43.0,-1.0,0.0,NaN
24,Belgium,G,12.0,0.0,0.0,1.0,5.0,Panama,13.0,NaN,NaN,Tunisia,29.0,0.0,0.0,England,45.0,-17.0,-70.0,NaN
25,Panama,G,0.0,0.0,0.0,0.0,56.0,Belgium,13.0,NaN,NaN,England,30.0,NaN,NaN,Tunisia,46.0,NaN,NaN,NaN
26,Tunisia,G,4.0,0.0,0.0,0.0,27.0,England,14.0,-1.0,-2.0,Belgium,29.0,0.0,0.0,Panama,46.0,NaN,NaN,NaN
27,England,G,14.0,1.0,1.0,2.0,15.0,Tunisia,14.0,1.0,2.0,Panama,30.0,NaN,NaN,Belgium,45.0,17.0,70.0,NaN
28,Poland,H,7.0,0.0,0.0,2.0,7.0,Senegal,15.0,NaN,NaN,Columbia,31.0,NaN,NaN,Japan,47.0,2.0,3.0,NaN
29,Senegal,H,1.0,0.0,0.0,0.0,23.0,Poland,15.0,NaN,NaN,Japan,32.0,2.0,3.0,Columbia,48.0,0.0,0.0,NaN
30,Columbia,H,5.0,0.0,0.0,0.0,13.0,Japan,16.0,2.0,2.0,Poland,31.0,NaN,NaN,Senegal,48.0,0.0,0.0,NaN
31,Japan,H,5.0,0.0,0.0,0.0,55.0,Columbia,16.0,-2.0,-2.0,Senegal,32.0,-2.0,-3.0,Poland,47.0,-2.0,-3.0,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
dataframe=pd.read_csv("/content/drive/MyDrive/World Cup 2018 Dataset.csv")
dataframe

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN
5,Spain,B,14.0,1.0,1.0,2.0,6.0,Portugal,3.0,12.0,31.0,Iran,20.0,NaN,NaN,Morocco,36.0,5.0,7.0,NaN
6,Morocco,B,4.0,0.0,0.0,0.0,40.0,Iran,4.0,-2.0,-2.0,Portugal,19.0,1.0,2.0,Spain,36.0,-5.0,-7.0,NaN
7,IRAN,B,4.0,0.0,0.0,0.0,32.0,Morocco,4.0,2.0,2.0,Spain,20.0,NaN,NaN,Portugal,35.0,-2.0,-5.0,NaN
8,France,C,14.0,1.0,2.0,5.0,9.0,Australia,5.0,1.0,6.0,Peru,21.0,-1.0,-1.0,Denmark,37.0,4.0,9.0,NaN
9,Australia,C,4.0,0.0,0.0,0.0,39.0,France,5.0,-1.0,-6.0,Denmark,22.0,-1.0,-3.0,Peru,38.0,NaN,NaN,NaN
10,Peru,C,4.0,0.0,0.0,0.0,11.0,Denmark,6.0,NaN,NaN,France,21.0,1.0,1.0,Australia,38.0,NaN,NaN,NaN
11,Denmark,C,4.0,0.0,0.0,0.0,12.0,Peru,6.0,NaN,NaN,Australia,22.0,1.0,3.0,France,37.0,-4.0,-9.0,NaN
12,Argentina,D,16.0,2.0,5.0,5.0,4.0,Iceland,7.0,NaN,NaN,Croatia,23.0,1.0,0.0,Nigeria,39.0,3.0,1.0,NaN
13,Iceland,D,0.0,0.0,0.0,0.0,22.0,Argentina,7.0,NaN,NaN,Nigeria,24.0,1.0,3.0,Croatia,40.0,-3.0,-9.0,NaN
14,Croatia,D,4.0,0.0,0.0,1.0,17.0,Nigeria,8.0,NaN,NaN,Argentina,23.0,-1.0,0.0,Iceland,40.0,3.0,9.0,NaN
15,Nigeria,D,5.0,0.0,0.0,0.0,50.0,Croatia,8.0,NaN,NaN,Iceland,24.0,-1.0,-3.0,Argentina,39.0,-3.0,-1.0,NaN
16,Brazil,E,20.0,5.0,7.0,11.0,2.0,Switzerland,9.0,1.0,2.0,Costarica,25.0,8.0,19.0,Serbia,41.0,1.0,1.0,NaN
17,Switzerland,E,10.0,0.0,0.0,0.0,8.0,Brazil,9.0,-1.0,-2.0,Serbia,26.0,NaN,NaN,Costarica,42.0,0.0,1.0,NaN
18,Costarica,E,4.0,0.0,0.0,0.0,26.0,Serbia,10.0,NaN,NaN,Brazil,25.0,-8.0,-19.0,Switzerland,42.0,0.0,-1.0,NaN
19,Serbia,E,11.0,0.0,0.0,2.0,37.0,Costarica,10.0,NaN,NaN,Switzerland,26.0,NaN,NaN,Brazil,41.0,-1.0,-1.0,NaN
20,Germany,F,18.0,4.0,8.0,13.0,1.0,Mexico,11.0,4.0,13.0,Sweden,27.0,2.0,10.0,Korea,43.0,1.0,0.0,NaN
21,Mexico,F,15.0,0.0,0.0,0.0,16.0,Germany,11.0,-4.0,-13.0,Korea,28.0,1.0,12.0,Sweden,44.0,-2.0,-3.0,NaN
22,Sweden,F,11.0,0.0,1.0,4.0,18.0,Korea,12.0,1.0,2.0,Germany,27.0,-2.0,-10.0,Mexico,44.0,2.0,3.0,NaN
23,Korea,F,9.0,0.0,0.0,1.0,59.0,Sweden,12.0,-1.0,-2.0,Mexico,28.0,-1.0,-10.0,Germany,43.0,-1.0,0.0,NaN
24,Belgium,G,12.0,0.0,0.0,1.0,5.0,Panama,13.0,NaN,NaN,Tunisia,29.0,0.0,0.0,England,45.0,-17.0,-70.0,NaN
25,Panama,G,0.0,0.0,0.0,0.0,56.0,Belgium,13.0,NaN,NaN,England,30.0,NaN,NaN,Tunisia,46.0,NaN,NaN,NaN
26,Tunisia,G,4.0,0.0,0.0,0.0,27.0,England,14.0,-1.0,-2.0,Belgium,29.0,0.0,0.0,Panama,46.0,NaN,NaN,NaN
27,England,G,14.0,1.0,1.0,2.0,15.0,Tunisia,14.0,1.0,2.0,Panama,30.0,NaN,NaN,Belgium,45.0,17.0,70.0,NaN
28,Poland,H,7.0,0.0,0.0,2.0,7.0,Senegal,15.0,NaN,NaN,Columbia,31.0,NaN,NaN,Japan,47.0,2.0,3.0,NaN
29,Senegal,H,1.0,0.0,0.0,0.0,23.0,Poland,15.0,NaN,NaN,Japan,32.0,2.0,3.0,Columbia,48.0,0.0,0.0,NaN
30,Columbia,H,5.0,0.0,0.0,0.0,13.0,Japan,16.0,2.0,2.0,Poland,31.0,NaN,NaN,Senegal,48.0,0.0,0.0,NaN
31,Japan,H,5.0,0.0,0.0,0.0,55.0,Columbia,16.0,-2.0,-2.0,Senegal,32.0,-2.0,-3.0,Poland,47.0,-2.0,-3.0,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
dataframe.tail(10)

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
23,Korea,F,9.0,0.0,0.0,1.0,59.0,Sweden,12.0,-1.0,-2.0,Mexico,28.0,-1.0,-10.0,Germany,43.0,-1.0,0.0,NaN
24,Belgium,G,12.0,0.0,0.0,1.0,5.0,Panama,13.0,NaN,NaN,Tunisia,29.0,0.0,0.0,England,45.0,-17.0,-70.0,NaN
25,Panama,G,0.0,0.0,0.0,0.0,56.0,Belgium,13.0,NaN,NaN,England,30.0,NaN,NaN,Tunisia,46.0,NaN,NaN,NaN
26,Tunisia,G,4.0,0.0,0.0,0.0,27.0,England,14.0,-1.0,-2.0,Belgium,29.0,0.0,0.0,Panama,46.0,NaN,NaN,NaN
27,England,G,14.0,1.0,1.0,2.0,15.0,Tunisia,14.0,1.0,2.0,Panama,30.0,NaN,NaN,Belgium,45.0,17.0,70.0,NaN
28,Poland,H,7.0,0.0,0.0,2.0,7.0,Senegal,15.0,NaN,NaN,Columbia,31.0,NaN,NaN,Japan,47.0,2.0,3.0,NaN
29,Senegal,H,1.0,0.0,0.0,0.0,23.0,Poland,15.0,NaN,NaN,Japan,32.0,2.0,3.0,Columbia,48.0,0.0,0.0,NaN
30,Columbia,H,5.0,0.0,0.0,0.0,13.0,Japan,16.0,2.0,2.0,Poland,31.0,NaN,NaN,Senegal,48.0,0.0,0.0,NaN
31,Japan,H,5.0,0.0,0.0,0.0,55.0,Columbia,16.0,-2.0,-2.0,Senegal,32.0,-2.0,-3.0,Poland,47.0,-2.0,-3.0,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
dataframe.head(20)

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN
5,Spain,B,14.0,1.0,1.0,2.0,6.0,Portugal,3.0,12.0,31.0,Iran,20.0,NaN,NaN,Morocco,36.0,5.0,7.0,NaN
6,Morocco,B,4.0,0.0,0.0,0.0,40.0,Iran,4.0,-2.0,-2.0,Portugal,19.0,1.0,2.0,Spain,36.0,-5.0,-7.0,NaN
7,IRAN,B,4.0,0.0,0.0,0.0,32.0,Morocco,4.0,2.0,2.0,Spain,20.0,NaN,NaN,Portugal,35.0,-2.0,-5.0,NaN
8,France,C,14.0,1.0,2.0,5.0,9.0,Australia,5.0,1.0,6.0,Peru,21.0,-1.0,-1.0,Denmark,37.0,4.0,9.0,NaN
9,Australia,C,4.0,0.0,0.0,0.0,39.0,France,5.0,-1.0,-6.0,Denmark,22.0,-1.0,-3.0,Peru,38.0,NaN,NaN,NaN
10,Peru,C,4.0,0.0,0.0,0.0,11.0,Denmark,6.0,NaN,NaN,France,21.0,1.0,1.0,Australia,38.0,NaN,NaN,NaN
11,Denmark,C,4.0,0.0,0.0,0.0,12.0,Peru,6.0,NaN,NaN,Australia,22.0,1.0,3.0,France,37.0,-4.0,-9.0,NaN
12,Argentina,D,16.0,2.0,5.0,5.0,4.0,Iceland,7.0,NaN,NaN,Croatia,23.0,1.0,0.0,Nigeria,39.0,3.0,1.0,NaN
13,Iceland,D,0.0,0.0,0.0,0.0,22.0,Argentina,7.0,NaN,NaN,Nigeria,24.0,1.0,3.0,Croatia,40.0,-3.0,-9.0,NaN
14,Croatia,D,4.0,0.0,0.0,1.0,17.0,Nigeria,8.0,NaN,NaN,Argentina,23.0,-1.0,0.0,Iceland,40.0,3.0,9.0,NaN
15,Nigeria,D,5.0,0.0,0.0,0.0,50.0,Croatia,8.0,NaN,NaN,Iceland,24.0,-1.0,-3.0,Argentina,39.0,-3.0,-1.0,NaN
16,Brazil,E,20.0,5.0,7.0,11.0,2.0,Switzerland,9.0,1.0,2.0,Costarica,25.0,8.0,19.0,Serbia,41.0,1.0,1.0,NaN
17,Switzerland,E,10.0,0.0,0.0,0.0,8.0,Brazil,9.0,-1.0,-2.0,Serbia,26.0,NaN,NaN,Costarica,42.0,0.0,1.0,NaN
18,Costarica,E,4.0,0.0,0.0,0.0,26.0,Serbia,10.0,NaN,NaN,Brazil,25.0,-8.0,-19.0,Switzerland,42.0,0.0,-1.0,NaN
19,Serbia,E,11.0,0.0,0.0,2.0,37.0,Costarica,10.0,NaN,NaN,Switzerland,26.0,NaN,NaN,Brazil,41.0,-1.0,-1.0,NaN

In [14]:
type(dataframe)

pandas.core.frame.DataFrame

In [15]:
dataframe.dtypes

Team                                       object
Group                                      object
Previous \nappearances                    float64
Previous \ntitles                         float64
Previous\n finals                         float64
Previous\n semifinals                     float64
Current \nFIFA rank                       float64
First match \nagainst                      object
Match index                               float64
history with \nfirst opponent\n W-L       float64
history with\n first opponent\n goals     float64
Second match\n against                     object
Match index.1                             float64
history with\n second opponent\n W-L      float64
history with\n second opponent\n goals    float64
Third match\n against                      object
Match index.2                             float64
history with\n third opponent\n W-L       float64
history with\n third opponent\n goals     float64
Unnamed: 19                               float64
dtype: object

In [21]:
dataframe[["Team","Group"]]

            Team Group
0         Russia     A
1   Saudi Arabia     A
2          Egypt     A
3        Uruguay     A
4        Porugal     B
5          Spain     B
6        Morocco     B
7           IRAN     B
8         France     C
9      Australia     C
10          Peru     C
11       Denmark     C
12     Argentina     D
13       Iceland     D
14       Croatia     D
15       Nigeria     D
16        Brazil     E
17   Switzerland     E
18     Costarica     E
19        Serbia     E
20       Germany     F
21        Mexico     F
22        Sweden     F
23         Korea     F
24       Belgium     G
25        Panama     G
26       Tunisia     G
27       England     G
28        Poland     H
29       Senegal     H
30      Columbia     H
31         Japan     H
32           NaN   NaN

In [23]:
dataframe.shape

(33, 20)